#ifndef C3_MEDIAN_FILTER_PLUGIN_GLOBAL_H
#define C3_MEDIAN_FILTER_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(C3_MEDIAN_FILTER_PLUGIN_LIBRARY)
#  define C3_MEDIAN_FILTER_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define C3_MEDIAN_FILTER_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // C3_MEDIAN_FILTER_PLUGIN_GLOBAL_H
